### PR TITLE
log exception raised from route_request_to_callbacks

### PR DESCRIPTION
**Pull request by davidharrigan**
Add logging for exception raised from processing the callback function.

### CODE REVIEW

**Comment by GregHilston** [comment]
@davidharrigan Ok just to be clear, the goal of these changes are to:
- ensure anyone using the library can define their own logger
- any unexpected crashes the library experiences won't crash anyone's usage of it, but rather will inform them

Did I understand what you did?

**Comment by davidharrigan** [comment]
> ensure anyone using the library can define their own logger

Yes - I believe it is encouraged to add NullHandler to the top-level logger - but here you are defining the NullHandler for each `__name__` namespace. So in order for the consumer to override the logging handlers provided here, it is required to override all of the loggers.  I can update the code here to add the handler to only the top-level namespace if you'd like.

https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

> any unexpected crashes the library experiences won't crash anyone's usage of it, but rather will inform them

Yes this small update will do two things:
- Do not crash the bot if the "callback" raises an exception
- Log the exception and the traceback

**Comment by GregHilston** [comment]
Ok, I follow everything you've written here. 

Can you show me this? 

>  I can update the code here to add the handler to only the top-level namespace if you'd like.

**Comment by davidharrigan** [comment]
i've added the top level logger

now you can configure this library to log to whatever by overriding the `simple_slack_bot` logger like so:
```python
import logging
from logging.config import dictConfig

PATH = os.path.dirname(os.path.realpath(__file__))
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console':{
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'rotate': {
            'level': 'INFO',
            'formatter': 'verbose',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(PATH, 'logs/dnd.log'),
            'when': 'midnight',
            'backupCount': 7,
        }
    },
    'loggers': {
        'simple_slack_bot': {
            'handlers': ['console', 'rotate'],
            'level': 'INFO'
        }
    }
}
dictConfig(LOGGING)
```

**Comment by GregHilston** [comment]
Ok the only thing I think I'll fix is the `logs/dnd.log`, as this will be for simple slack bot. 

so I'd change i'll change it to `logs/simple_slack_bot.log`, you cool with that?

**Comment by GregHilston** [comment]
I'm dumb. You showed me an example. I thought the PR was showing me your commit. haha

**Pull request merged**
