### PR TITLE
Support channel replies

### LINKED ISSUE #35: Question: Support for Slack threads?
How would I go about having the Slack bot respond in a Slack thread? I am familiar with the Slack API, but I'm not seeing a simple way to respond to a message in a thread. 

Is that something that this simple-slack-bot framework is capable of doing? 

EDIT: I modified that title to include reactions as in the comments section I have started a conversation about adding support for threads and reactions.

### PR DESCRIPTION
**Pull request by GregHilston**
Added support to reply to channels when subscribing to the message event. Had to upgrade the dependency on Slacker, as the version I had pinned did not support threads, which is probably why I didn't look into this in the first place.

As noted in the commit messages, this implementation is not great. Specifically the code that only propagates the event if there is not `subtype`. This was the first fix I thought of when realizing that a reply to a thread sends three slack events. For example:

```
{'type': 'message', 'subtype': 'message_replied', 'hidden': True, 'message': {'client_msg_id': '8f047d3b-bb77-429f-a75d-d2f0cdb25bd3', 'type': 'message', 'text': 'hey', 'user': 'U389XUHT2', 'ts': '1591449692.004800', 'team': 'T38AP97Q9', 'blocks': [{'type': 'rich_text', 'block_id': 'GJc5', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'hey'}]}]}], 'thread_ts': '1591449692.004800', 'reply_count': 24, 'reply_users_count': 2, 'latest_reply': '1591454854.014600', 'reply_users': ['U389XUHT2', 'B0117UPS0UR']}, 'channel': 'C3FAX3UCV', 'event_ts': '1591454854.014700', 'ts': '1591454854.014700'},
{'client_msg_id': '08d82eb4-543b-495c-ae6e-0e104805840a', 'suppress_notification': False, 'type': 'message', 'text': 'THREAD', 'user': 'U389XUHT2', 'team': 'T38AP97Q9', 'blocks': [{'type': 'rich_text', 'block_id': 'I97hA', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'THREAD'}]}]}], 'thread_ts': '1591449692.004800', 'source_team': 'T38AP97Q9', 'user_team': 'T38AP97Q9', 'channel': 'C3FAX3UCV', 'event_ts': '1591454854.014600', 'ts': '1591454854.014600'},
{'type': 'message', 'subtype': 'message_replied', 'hidden': True, 'message': {'client_msg_id': '8f047d3b-bb77-429f-a75d-d2f0cdb25bd3', 'type': 'message', 'text': 'hey', 'user': 'U389XUHT2', 'ts': '1591449692.004800', 'team': 'T38AP97Q9', 'blocks': [{'type': 'rich_text', 'block_id': 'GJc5', 'elements': [{'type': 'rich_text_section', 'elements': [{'type': 'text', 'text': 'hey'}]}]}], 'thread_ts': '1591449692.004800', 'reply_count': 25, 'reply_users_count': 2, 'latest_reply': '1591454856.014900', 'reply_users': ['U389XUHT2', 'B0117UPS0UR']}, 'channel': 'C3FAX3UCV', 'event_ts': '1591454856.015000', 'ts': '1591454856.015000'}
```

If the `subtype` check is not implemented and one replies to a threaded message, you end up with one thread reply and two channel replies. I'm also unsure why one gets two events that are almost identical referencing the channel itself.

I 100% believe this `subtype` check will have unintended consequences but I have not discovered any yet.

Since this is my first public pull request, I'll wait on merging until reviewed. Please comment/question/challenge anything I've written. No hard feelings here at all.

@coltenkrauter 

Closes #35

### CODE REVIEW

**Comment by GregHilston** [comment]
Decided to add the old unit tests to master, after getting circle CI to run and merge them here

**Comment by coltenkrauter** [comment]
Hey man, sorry it took me so long to see this. I intend to review it this week 👍

**Comment by GregHilston** [comment]
Not a problem at all man! Happy you even got back to me

**Comment by coltenkrauter** [comment]
Hey, so I am trying to run the code locally and I am running into an error upon connecting, 
**[ERROR] This method is retired and can no longer be used. Please use conversations.list or users.conversations instead.**

I created an issue: #41

**Comment by GregHilston** [comment]
@coltenkrauter I somehow never saw your reply but did see the issue you made. I'll merge this as it works for my old bot and resolve #41 to get new bots to work. Thanks for documenting this!

**Pull request merged**
