### PR TITLE
Update pip dependency versions

### PR DESCRIPTION
**Pull request by coltenkrauter**

### CODE REVIEW

**Comment by coltenkrauter** [comment]
@GregHilston Did I break something?

**Comment by GregHilston** [comment]
@coltenkrauter I don't think the CICD error is anything you did, rather I have an old config. Let me fix my old config and rerun your PR and prove it works, which I'm sure it does.

Then i'll merge it!

**Comment by GregHilston** [comment]
Remembered that I never used Circle CI on this ha merging

**Comment by coltenkrauter** [comment]
@GregHilston How do we go about publishing the update to PyPI? Do you just need to create a GitHub release? I imagine you have some automation to do that for you?

**Comment by GregHilston** [comment]
@coltenkrauter I don't believe I ever automated this. 

I just confirmed that everything works on my end after merging your PR and the two automated security PRs, so that's huge news.

Let me get the PyPi file (`setup.py`) up to date and remember how to push a release. 

When I'm doing these things I'll either document it in the README.md and provide some script or automate it. That way we're on the same page on how its done. 

Sound good?

**Comment by coltenkrauter** [comment]
Sounds great 👍

**Pull request merged**
