### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ramast**
Change the way callback functions respond to user.
breaks backward compatibility, Please don't merge to master

### CODE REVIEW

**Comment by GregHilston** [comment]
@ramast What does "Please don't" mean? haha

**Comment by ramast** [comment]
Corrected it :)

**Comment by GregHilston** [comment]
Checked over the changes and they all look great! I'm going to do a local merge over lunch and test everything out before accepting the pull request. I'm thinking we call this effort "Milestone 2.0

**Comment by ramast** [comment]
Absolutely, Once we finish all the improvements we discussed, test it, maybe add test cases?
we should release it to master under the name Milestone 2 (or any other name you like).

I'll create some issues with the things I think can be improved then we discuss each one on it's own thread

**Comment by GregHilston** [comment]
This looks excellent! I like the structure of the Request class. It adds alot to the library! Merging now

**Pull request merged**
